TASK1 = 'station_keeping'
TASK2 = 'wayfinding'
TASK3 = 'perception'
TASK4 = ''
TASK5 = ''
TASK6 = ''

STATE_ESTIMATION = [TASK1, TASK2, TASK3, TASK4, TASK5, TASK6]
TRAJECTORY_GENERATION_TASK1 = [TASK1]
TRAJECTORY_GENERATION_TASK2 = [TASK2]
TRAJECTORY_TRACKER_NODE = [TASK1, TASK2, TASK4, TASK5, TASK6]
HEADING_CONTROL_NODE = [TASK1, TASK2, TASK4, TASK5, TASK6]
CONTROL_ALLOCATION_TABLE = [TASK1, TASK2, TASK4, TASK5, TASK6]
OBJECT_CHARACTERIZATION = [TASK3, TASK4, TASK5, TASK6]
OBJECT_LOCALIZATION = [TASK3, TASK4, TASK5, TASK6]
